spring:
    datasource:
        username: postgres
        password: postgres
        url: jdbc:postgresql://localhost:8050/InstantChat
    jpa:
        hibernate:
            ddl-auto: update

server:
    port: 8081

grpc:
    server:
        port: 9091

    client:
        grpc-server-conversation: # gRPC server name
            address: 'static://127.0.0.1:9092'
            enableKeepAlive: true
            keepAliveWithoutCalls: true
            negotiationType: plaintext
