spring:
    datasource:
        username: postgres
        password: postgres
        url: jdbc:postgresql://localhost:8050/InstantChat
    jpa:
        hibernate:
            ddl-auto: update

    # ref: https://docs.spring.io/spring-session/reference/guides/boot-redis.html
    session:
        store:
            type: redis

        redis:
            namespace: spring:session
    data:
        redis:
            # cluster
            cluster.nodes: ${REDIS_URL}

            # single-node
    #            host: ${REDIS_URL}
    #            port: 6379

    kafka:
        bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
        consumer.group-id: ${random.long}

server:
    port: 8081

    error:
        include-message: always

frontend:
    url: http://localhost:3000

grpc:
    server:
        port: 9091

    client:
        grpc-server-message: # gRPC server name
            address: 'static://127.0.0.1:9092'
            enableKeepAlive: true
            keepAliveWithoutCalls: true
            negotiationType: plaintext

        grpc-server-account: # gRPC server name
            address: 'static://127.0.0.1:9094'
            enableKeepAlive: true
            keepAliveWithoutCalls: true
            negotiationType: plaintext

