# application configuration for local k8 minikube

spring:
    datasource:
        username: ${PG_USERNAME}
        password: ${PG_PASSWORD}
        url: ${PG_URL}
    jpa:
        hibernate:
            ddl-auto: update

    # ref: https://docs.spring.io/spring-session/reference/guides/boot-redis.html
    session:
        store:
            type: redis

        redis:
            namespace: spring:session
    data:
        redis:
            host: ${REDIS_URL}
            port: 6379

server:
    port: 8080

    servlet:
        session:
            timeout: 360000  # session timeout, 100 hrs

            cookie:
                same-site: None   # set cookie, https

amazon:
    aws:
        accesskey: ${AWS_ACCESS_KEY}
        secretkey: ${AWS_SECRET_KEY}

    s3:
        bucketname: ${S3_BUCKET_NAME}


frontend:
    url: ${FRONTEND_URL}

grpc:
    server:
        port: 9090

    client:
        # microservices
        # find gRPC server by dns
        # ref: https://yidongnan.github.io/grpc-spring-boot-starter/en/client/configuration.html

        grpc-server-channel-mapping: # gRPC server name
            address: 'dns:///channel-mapping-service:9090'
            enableKeepAlive: true
            keepAliveWithoutCalls: true
            negotiationType: plaintext

        grpc-server-conversation: # gRPC server name
            address: 'dns:///conversation-service:9090'
            enableKeepAlive: true
            keepAliveWithoutCalls: true
            negotiationType: plaintext
