spring:
    datasource:
        username: postgres
        password: postgres
        url: jdbc:postgresql://localhost:8050/InstantChat
    jpa:
        hibernate:
            ddl-auto: update

    # ref: https://docs.spring.io/spring-session/reference/guides/boot-redis.html
    session:
        store:
            type: redis

        redis:
            namespace: spring:session
    data:
        redis:
            # cluster
            cluster.nodes: ${REDIS_URL}

            # single-node
#            host: ${REDIS_URL}
#            port: 6379

server:
    port: 8084

    servlet:
        session:
            timeout: 360000  # session timeout, 100 hrs

            cookie:
                same-site: Lax   # set cookie, https
amazon:
    aws:
        accesskey: ${AWS_ACCESS_KEY}
        secretkey: ${AWS_SECRET_KEY}

    s3:
        bucketname: ${S3_BUCKET_NAME}

frontend:
    url: http://localhost:3000

grpc:
    server:
        port: 9094